aa

diff --git a/.github/workflows/post-remind-to-discord-clean-aqua-filter.yml b/.github/workflows/post-remind-to-discord-clean-aqua-filter.yml
--- a/.github/workflows/post-remind-to-discord-clean-aqua-filter.yml
+++ b/.github/workflows/post-remind-to-discord-clean-aqua-filter.yml
@@ -48,3 +48,11 @@ jobs:
             "🐥 < AQUAのフィルター掃除をするﾋﾟﾖ！ @everyone" \
             "Click me!" \
             "お掃除お疲れ様ﾋﾟﾖ！"
+        continue-on-error: true
+
+      - name: Check for errors
+        run: |
+          if [ $? -ne 0 ]; then
+            echo "Discord notification failed"
+            exit 1
+          fi
